stages:
  - lint
  - test
  - analyze

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "master"

frontend.eslint:
  stage: lint
  image: node:16-alpine3.13
  script:
    - cd frontend
    - npm install --quiet
    - npm run lint

backend.checkstyle:
  stage: lint
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle --no-daemon checkstyleMain checkstyleTest

backend.test:
  stage: test
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle --no-daemon clean test jacocoTestReport --rerun-tasks

backend.sonarqube:
  stage: analyze
  image: gradle:7.2.0-jdk11
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - backend/.sonar/cache
  allow_failure: true
  script:
    - cd backend
    - gradle --no-daemon jacocoTestReport sonarqube

frontend.sonarqube:
  stage: analyze
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    EXCLUDE: node_modules/**
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - frontend/.sonar/cache
  allow_failure: true
  script:
    - cd frontend
    - sonar-scanner
        -Dsonar.qualitygate.wait=true
        -Dsonar.sources=.
        -Dsonar.language=js
        -Dsonar.projectKey=rfobaden-incident-manager_frontend
        -Dsonar.projectName=rfobaden-incident-manager_frontend

variables:
  GIT_DEPTH: 0

cache:
  key: ${CI_JOB_NAME}
  paths:
    - backend/.gradle
    - frontend/node_modules