stages:
  - lint
  - test
  - analyze

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "master"

frontend.eslint:
  stage: lint
  image: node:16-alpine3.13
  script:
    - cd frontend
    - npm install --quiet
    - npm run lint

backend.checkstyle:
  stage: lint
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle --no-daemon checkstyleMain checkstyleTest

backend.test:
  stage: test
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle clean test --rerun-tasks

backend.sonarqube:
  stage: analyze
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    GIT_DEPTH: 0
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - backend/.sonar/cache
  allow_failure: true
  script:
    - cd backend
    - sonar-scanner
      -Dsonar.qualitygate.wait=true
      -Dsonar.host.url=$CI_SONARQUBE_HOST_URL
      -Dsonar.login=$CI_SONARQUBE_TOKEN
      -Dsonar.sources=.
      -Dsonar.language=java
      -Dsonar.projectKey=rfobaden-incident-manager_backend
      -Dsonar.projectName=rfobaden-incident-manager_backend

frontend.sonarqube:
  stage: analyze
  image: sonarsource/sonar-scanner-cli:latest
  variables:
    GIT_DEPTH: 0
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - frontend/.sonar/cache
  allow_failure: true
  script:
    - cd frontend
    - npm install typescript
    - sonar-scanner
        -Dsonar.qualitygate.wait=true
        -Dsonar.host.url=$CI_SONARQUBE_HOST_URL
        -Dsonar.login=$CI_SONARQUBE_TOKEN
        -Dsonar.sources=.
        -Dsonar.language=js
        -Dsonar.projectKey=rfobaden-incident-manager_frontend
        -Dsonar.projectName=rfobaden-incident-manager_frontend

cache:
  key: ${CI_JOB_NAME}
  paths:
    - backend/.gradle
