stages:
  - lint
  - test
  - analyze

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "master"

frontend.eslint:
  stage: lint
  image: node:16-alpine3.13
  script:
    - cd frontend
    - npm install --quiet
    - npm run lint

backend.checkstyle:
  stage: lint
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle --no-daemon checkstyleMain checkstyleTest

backend.test:
  stage: test
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle clean test --rerun-tasks

analyze.sonarqube.backend:
  stage: analyze
  image: gradle:7.2.0-jdk11
  allow_failure: false
  script:
    - cd backend
    - gradle sonarqube

analyze.sonarqube.frontend:
  stage: analyze
  image: sonarsource/sonar-scanner-cli:latest
  allow_failure: false
  script:
    - cd frontend
    - sonar-scanner -Dsonar.host.url=$CI_SONARQUBE_HOST_URL
      -Dsonar.login=$CI_SONARQUBE_TOKEN
      -Dsonar.projectKey=rfobaden-incident-manager-frontend
      -Dsonar.projectName=rfobaden-incident-manager-frontend
      -Dsonar.sources=.


cache:
  key: ${CI_JOB_NAME}
  paths:
    - backend/.gradle
    - .sonar/cache
