image:
  name: docker:20.10.9
  entrypoint: ["sh", "-c"]

services:
  - docker:20.10.9-dind

before_script:
  - docker info

stages:
  - lint

eslint:
  stage: lint
  script:
    - docker-compose run frontend "npm install && npm run lint"

variables:
  DOCKER_DRIVER: overlay2
