stages:
  - lint
  - test
  - analyze

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "development" || $CI_COMMIT_BRANCH == "master"

frontend.eslint:
  stage: lint
  image: node:16-alpine3.11
  script:
    - cd frontend
    - npm install --quiet
    - npm run lint

backend.checkstyle:
  stage: lint
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle --no-daemon checkstyleMain checkstyleTest

backend.test:
  stage: test
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle clean test --rerun-tasks

analyze.sonarqube.backend:
  stage: analyze
  image: gradle:7.2.0-jdk11
  allow_failure: false
  script:
    - cd backend
    - gradle sonarqube

analyze.sonarqube.frontend:
  stage: analyze
  image: node:16-alpine3.11
  allow_failure: false
  before_script:
    - cd frontend
    - apk --update add openjdk8-jre
    - sed -i 's/use_embedded_jre=true/use_embedded_jre=false/g' /root/.sonar/native-sonar-scanner/sonar-scanner-4.4.0.2170-linux/bin/sonar-scanner
    - npm install --quiet

  script:
    - npm run sonar-scanner


cache:
  key: ${CI_JOB_NAME}
  paths:
    - backend/.gradle
    - .sonar/cache
