image:
  name: docker:20.10.9-alpine3.14
  entrypoint: ["sh", "-c"]

services:
  - 20.10.9-dind-alpine3.14

before_script:
  - docker info

stages:
  - lint

eslint:
  stage: lint
  script:
    - docker-compose run frontend "npm install && npm run lint"

variables:
  DOCKER_DRIVER: overlay2
