stages:
  - lint

frontend.eslint:
  stage: lint
  image: node:16-alpine3.11
  script:
    - cd frontend
    - npm install --quiet
    - npm run lint
  only:
    - master
    - development

backend.checkstyle:
  stage: lint
  image: gradle:7.2.0-jdk11
  script:
    - cd backend
    - gradle --no-daemon checkstyleMain checkstyleTest
  only:
    - master
    - development

cache:
  paths:
    - backend/.gradle
    - frontend/node_modules/
