image:
  name: docker:20.10.9
  entrypoint: ["sh", "-c"]

services:
  - name: docker:20.10.9-dind
    alias: dockerhost

before_script:
  - docker info

stages:
  - lint

eslint:
  stage: lint
  script:
    - docker-compose run frontend "npm install && npm run lint"

variables:
  DOCKER_HOST: tcp://dockerhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  
