image:
  name: docker/compose:alpine-1.29.2
  entrypoint: ["sh", "-c"]

services:
  - name: docker:20.10.9-dind-alpine3.14
    alias: dockerhost

before_script:
  - docker-compose run --no-deps --detach frontend sh
  - docker-compose run --no-deps --detach backend sh
  - docker-compose exec frontend "npm install"

after_script:
  - docker-compose down

stages:
  - lint

eslint:
  stage: lint
  script:
    - docker-compose exec frontend "npm run lint"

variables:
  DOCKER_HOST: tcp://dockerhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  
