version: "3.9"
services:
  frontend:
    image: node:16-alpine3.15
    command: ["npm", "run", "dev"]
    working_dir: /app
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_RFO_BACKEND_URL=${RFO_BACKEND_URL}
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - ./frontend:/app
      - frontend.node_modules:/app/node_modules
    depends_on:
      - backend
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '1GB'

  backend:
    image: gradle:7.3.1-jdk11-alpine
    command: ["sh", "dev.sh"]
    working_dir: /app
    restart: always
    networks:
      default:
        aliases:
          - backend-${RFO_STAGE}
    ports:
      - "3001:8080"
      - "5005:5005"
    environment:
      - TZ=Europe/Zurich
    volumes:
      - ./backend:/app
      - backend.cache:/home/gradle/.gradle
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '3GB'

  database:
    image: mysql:8.0
    command:
      - "--default-authentication-plugin=mysql_native_password"
    restart: always
    environment:
      - MYSQL_DATABASE=${RFO_DATABASE_NAME}
      - MYSQL_USER=${RFO_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${RFO_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${RFO_DATABASE_ROOT_PASSWORD}
    ports:
      - "3002:3306"
    volumes:
      - database:/var/lib/mysql
      - ./data-sample.sql:/data-sample.sql
      - ./data-prod.sql:/data-prod.sql
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '500MB'


volumes:
  frontend.node_modules:
  backend.cache:
  database:
