version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend.dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_ENDPOINT=http://localhost:4000
    ports:
      - "4000:3000"
      - "4035:3035"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    ports:
      - "4001:8080"
      - "6005:5005" 
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "4002:3306"
    volumes:
      - database:/var/lib/mysql
  

volumes:
  database: