version: "3.9"
services:
  frontend:
    image: node:16-alpine3.11
    working_dir: /app
    command: [ "npm", "run", "dev" ]
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_BACKEND_ENDPOINT=http://localhost:3001
    ports:
      - "${FRONTEND_APP_PORT}:3000"
      - "${FRONTENT_WEBPACK_PORT}:3035"
    volumes:
      - ./frontend:/app
      - frontend.node_modules:/app/node_modules
    depends_on:
      - backend
    tmpfs:
      - /app/.next:mode=777,uid=1000,gid=1000

  backend:
    image: gradle:7.2.0-jdk11
    working_dir: /app
    command: > 
      sh -c "gradle --stop && 
            gradle build && 
            gradle bootRun --no-build-cache"
    ports:
      - "${BACKEND_APP_PORT}:8080"
      - "${BACKEND_DEBUGGER_PORT}:5005" 
    environment:
      - TZ=Europe/Zurich
    volumes:
      - ./backend:/app
      - backend.gradle-global:/home/gradle/.gradle
      - backend.gradle-local:/app/.gradle
      - /etc/localtime:/etc/localtime:ro
    tmpfs:
      - /app/build
    depends_on:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes:
      - database:/var/lib/mysql
  

volumes:
  frontend.node_modules:
  backend.gradle-local:
  backend.gradle-global:
  database: