FROM node:16-alpine3.11
WORKDIR /app
COPY frontend/package.json .

RUN npm install
COPY frontend/ .

ARG NEXT_PUBLIC_BACKEND_ENDPOINT
ENV NEXT_PUBLIC_BACKEND_ENDPOINT ${NEXT_PUBLIC_BACKEND_ENDPOINT}

CMD npm run dev