spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/${RFO_DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${RFO_DATABASE_USERNAME}
    password: ${RFO_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
#  mail:
#    host: lx52.hoststar.hosting
#    port: 587 #465
#    username: im@rfo-baden.ch
#    password: 54Rf0_ImT00l.17
#    protocol: smtp
##    test-connection: true
#    properties:
#      "mail.smtp.auth": true
#      "mail.smtp.ssl.enable": true

rfo:
  jwt:
    secret: ${RFO_JWT_SECRET}
  frontend:
    host: ${RFO_FRONTEND_HOST}