spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database:3306/${RFO_DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=false
    username: ${RFO_DATABASE_USERNAME}
    password: ${RFO_DATABASE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update

rfo:
  stage: ${RFO_STAGE}
  jwt:
    secret: ${RFO_JWT_SECRET}
  frontend:
    host: ${RFO_FRONTEND_HOST}
  mail:
    enable: true